### ISSUE TITLE
Bilgilendirme

### ISSUE THREAD

**Issue by mahammad** [arslanaybars/C-Programlama-Ornekleri#1]
1. program 24 hakkinda bilgi ala bilirmiyim? Teşekkürler.

**Comment by arslanaybars** [comment]
Program 24 mantıksal operatörlerin kullanımı göstermeyi amaçlayan bir program. x ve y değişkenlerimize başlangıçta hex degerler attıktan sonra en cok kullanılan mantıksal operatörler ile kullanıp sonuçları yazdırdım. Daha anlaşılabilmesi açısından yorum satırları ekledim şuan, umarım yardımcı olur. İyi çalışmalar

**Comment by mahammad** [comment]
Teşekkur edeerim projenizi hevesle takip ediyorum kolay gelsin :smile:
